---
name: lint & test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "tests/**"

jobs:
  build:
    # Name the Job
    name: test-code-base
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # set up python
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      # install dependencies
      - name: Install dependencies
        run: uv sync --all-extras

      # install pre-commit hooks
      - name: Install pre-commit hooks
        run: uv run pre-commit install

      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          uv run ruff check src/
          uv run mypy --config-file pyproject.toml src/
          uv run deptry .

      # run unit tests
      - name: Run unit-tests
        run: |
          set -o pipefail
          uv run pytest --cov=src --cov-report=xml --cov-fail-under=50 --junitxml=tests/pytest.xml | tee tests/pytest-coverage.txt

      # add content to GitHub summary
      - name: Pytest coverage GitHub summary
        run: |
          set -o pipefail
          echo '# Coverage report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat tests/pytest-coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '\n\n\n'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
