---
name: semantic-release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - release*
    paths:
      - 'src/**'
      - 'pyproject.toml'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    # Name the Job
    name: semantic-release
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    # Load all steps #
    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # set env variable
      - name: Set env variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # set up python
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      # install dependencies
      - name: Install dependencies
        run: uv sync --all-extras

      - name: Python Semantic Release to PyPI
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          uv run semantic-release publish --verbosity=DEBUG --define=branch=${{ env.BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
